name: nucypher-contracts
contracts_folder: contracts

plugins:
  - name: solidity
  - name: polygon
  - name: ape-etherscan

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 5.0.0
    config_override:
      solidity:
        version: 0.8.20
        evm_version: paris
  - name: openzeppelin-upgradeable
    github: OpenZeppelin/openzeppelin-contracts-upgradeable
    version: 5.0.0
  - name: fx-portal
    github: 0xPolygon/fx-portal
    version: 1.0.5
  - name: threshold
    github: threshold-network/solidity-contracts
    version: 1.2.1

solidity:
  version: 0.8.20
  evm_version: paris
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v5.0.0"
    - "@openzeppelin-upgradeable/contracts=openzeppelin-upgradeable/v5.0.0"
    - "@fx-portal/contracts=fx-portal/v1.0.5"
    - "@threshold/contracts=threshold/v1.2.1"

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 10
