dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.4.2
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2"
      - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.4.2"